# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peek < Formula
  desc "Observe AI agent sessions in real-time"
  homepage "https://github.com/bskyn/peek"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bskyn/peek/releases/download/v0.5.0/peek_darwin_amd64.tar.gz"
      sha256 "739c02a5cb010f304bb0148c1ccbf9c8d39c24c2cc201aeb2b3b040ea1469f56"

      define_method(:install) do
        bin.install "peek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bskyn/peek/releases/download/v0.5.0/peek_darwin_arm64.tar.gz"
      sha256 "2c8467e5fe74fff30d95943fd26f395ea01882d2a10608b45f6b162e61c5f6e2"

      define_method(:install) do
        bin.install "peek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bskyn/peek/releases/download/v0.5.0/peek_linux_amd64.tar.gz"
      sha256 "f326cdf6cb14b6fd41574586a82dc7a64186cbb117d563ada9350321d321a149"
      define_method(:install) do
        bin.install "peek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bskyn/peek/releases/download/v0.5.0/peek_linux_arm64.tar.gz"
      sha256 "941fb0ee28ded9f6b822d7ead7562a0d3d8119311eb7d68219b99e8e3ceec9f2"
      define_method(:install) do
        bin.install "peek"
      end
    end
  end
end
