# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peek < Formula
  desc "Observe AI agent sessions in real-time"
  homepage "https://github.com/bskyn/peek"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bskyn/peek/releases/download/v0.6.2/peek_darwin_amd64.tar.gz"
      sha256 "69b80d0dbea8b1261b88429bfb2eecd68487728c6eea8e9258ae2f4958939039"

      define_method(:install) do
        bin.install "peek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bskyn/peek/releases/download/v0.6.2/peek_darwin_arm64.tar.gz"
      sha256 "549e596c8d87d77104cc88a434e71324c786efb49acd0e197431737587df0235"

      define_method(:install) do
        bin.install "peek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bskyn/peek/releases/download/v0.6.2/peek_linux_amd64.tar.gz"
      sha256 "1af6f5501df2a0dd86a6da56cc6633b5241858fa8ff9ee2b70f98f7b3947ffcf"
      define_method(:install) do
        bin.install "peek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bskyn/peek/releases/download/v0.6.2/peek_linux_arm64.tar.gz"
      sha256 "ce5cc13b70cd2af76359f6cfc9cb3d17d261c666e193ef1a506db14411dc4dd5"
      define_method(:install) do
        bin.install "peek"
      end
    end
  end
end
