# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peek < Formula
  desc "Observe AI agent sessions in real-time"
  homepage "https://github.com/bskyn/peek"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bskyn/peek/releases/download/v0.3.0/peek_darwin_amd64.tar.gz"
      sha256 "8b20bb47e99d2b30e95d0daab30794872529959bb399cc7958df1246dfaf3b8b"

      define_method(:install) do
        bin.install "peek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bskyn/peek/releases/download/v0.3.0/peek_darwin_arm64.tar.gz"
      sha256 "68dc29b7170e9cb1462faf21a0cdb3340b936c0514c6b81310933e4db7c4b0c6"

      define_method(:install) do
        bin.install "peek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bskyn/peek/releases/download/v0.3.0/peek_linux_amd64.tar.gz"
      sha256 "4bde583d6f223ce60e419d0c0ad3f2f53d58dac9a14dd875565b932087797eeb"
      define_method(:install) do
        bin.install "peek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bskyn/peek/releases/download/v0.3.0/peek_linux_arm64.tar.gz"
      sha256 "3da9b6de9d178b9ea91136ae93f69b805e9845245d32d6f437264634b0437643"
      define_method(:install) do
        bin.install "peek"
      end
    end
  end
end
